<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="60801" started-at="2020-02-11T15:50:21Z" finished-at="2020-02-11T15:51:21Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="60801" started-at="2020-02-11T15:50:21Z" finished-at="2020-02-11T15:51:21Z">
      <class name="practise.NewContactVerfication">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:practise.NewContactVerfication@724af044]" name="beforeMethod" is-config="true" duration-ms="20114" started-at="2020-02-11T21:20:21Z" finished-at="2020-02-11T21:20:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="contactverify()[pri:0, instance:practise.NewContactVerfication@724af044]" name="contactverify" duration-ms="12800" started-at="2020-02-11T21:20:41Z" finished-at="2020-02-11T21:20:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactverify -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:practise.NewContactVerfication@724af044]" name="afterMethod" is-config="true" duration-ms="1507" started-at="2020-02-11T21:20:53Z" finished-at="2020-02-11T21:20:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:practise.NewContactVerfication@724af044]" name="beforeMethod" is-config="true" duration-ms="19822" started-at="2020-02-11T21:20:55Z" finished-at="2020-02-11T21:21:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="verifydetails()[pri:2, instance:practise.NewContactVerfication@724af044]" name="verifydetails" duration-ms="5153" started-at="2020-02-11T21:21:15Z" finished-at="2020-02-11T21:21:20Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[registration details are matched expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: registration details are matched expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at practise.NewContactVerfication.verifydetails(NewContactVerfication.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifydetails -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:practise.NewContactVerfication@724af044]" name="afterMethod" is-config="true" duration-ms="1373" started-at="2020-02-11T21:21:20Z" finished-at="2020-02-11T21:21:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- practise.NewContactVerfication -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
